package com.company.asset.domain.notification;

public enum NotificationType {
    RENTAL_REQUEST_CREATED,
    RENTAL_REQUEST_APPROVED,
    RENTAL_REQUEST_REJECTED,
    RENTAL_RETURN_REQUESTED,
    RENTAL_RETURN_CONFIRMED,
    SANCTION_CREATED,
    RESERVATION_CREATED,
    RESERVATION_CANCELED,
    RESERVATION_CHECKED_OUT,
    MAINTENANCE_CREATED,
    MAINTENANCE_CANCELED,
    RENTAL_REQUEST_CANCELED
}